patient:
  params:
    x: 55
    y: 56

spring:
  datasource:
    url: jdbc:h2:mem:patient-db;
    driverClassName: org.h2.Driver
    username: user
    password: passer@123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true